# Generated by Django 4.2.7 on 2023-12-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
