# Generated by Django 4.2.7 on 2023-12-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100, null=True)),
                ('ProductCategories', models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food')], max_length=50, null=True)),
                ('ProductPrice', models.PositiveBigIntegerField(null=True)),
                ('ProductQty', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
