# Generated by Django 4.2.7 on 2023-12-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlacementTime', models.DateField(auto_now=True)),
                ('CustomerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('OrderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.product')),
            ],
        ),
    ]
