# Generated by Django 4.2.7 on 2023-12-29 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SELL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalAmount', models.PositiveBigIntegerField(null=True)),
                ('PlacementTime', models.DateField(auto_now=True)),
                ('SellId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.product')),
                ('UserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
